application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: true
email_client:
  base_url: "localhost"
  sender_client: "test@gmail.com"
  authorization_token: "my-secret-token"